language: node_js
node_js:
  - 6

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run build
  - yarn test

deploy:
  provider: script
  script: ci/deploy.sh
  on:
    branch: master

env:
  global:
    - COMMIT_AUTHOR_EMAIL: "furyhunter600@gmail.com"
